### ISSUE TITLE
Where to store the images used by the operator?

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery-operator#1]
The operator will pull a node-feature-discovery container image that it manages. Do we have a repository to store the image?

**Comment by marquiz** [comment]
You mean NFD images? They are currently hosted ad quay.io:
https://quay.io/repository/kubernetes_incubator/node-feature-discovery

**Comment by marquiz** [comment]
This is still valid. There's a repo for the operator in quay.io:
https://quay.io/repository/kubernetes_incubator/node-feature-discovery-operator

/remove-lifecycle rotten

**Comment by marquiz** [comment]
We have the repo in https://quay.io/repository/kubernetes_incubator/node-feature-discovery-operator

However, going forward we might want to migrate to gcr.io

/remove-lifecycle stale

**Comment by marquiz** [comment]
How about using `k8s.gcr.io/nfd/`? Would sound like a logical place to me.

**Comment by ArangoGutierrez** [comment]
how would that not conflict with NFD the operand? how is the operand image named? maybe `k8s.gcr.io/nfdoperator/` describe better the image

**Comment by marquiz** [comment]
> ow would that not conflict with NFD the operand? how is the operand image named? maybe `k8s.gcr.io/nfdoperator/` describe better the image

We can have multiple "repositories" there. There is no technical problem having both images:
- `k8s.gcr.io/nfd/node-feature-discovery:vX.Y.Z`
- `k8s.gcr.io/nfd/node-feature-discovery-operator:vI.J.K`

Of course, we could request for a separate project like `k8s.gcr.io/nfd-operator/` which would make it, naturally, totally independent. But since the projects are so tightly coupled it might be justifiable and make sense to serve the images from the same place. WDYT? @zvonkok (?)

**Comment by ArangoGutierrez** [comment]
I am ok with `k8s.gcr.io/nfd/node-feature-discovery`

**Comment by marquiz** [comment]
You mean `k8s.gcr.io/nfd/node-feature-discovery-operator` (?) 😉  `k8s.gcr.io/nfd/node-feature-discovery` is reserved for the operand 😄

**Comment by ArangoGutierrez** [comment]
yup, I full agree with that image name/repo name
